version: '3.4'

volumes:
  dadosdb:

networks:
  frontend:
  backend:

services:

  mysql:
    image: "mysql"
    volumes:
      - dadosdb:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=10101010
      - bind-address=0.0.0.0

  dockertest:
    image: ${DOCKER_REGISTRY-}dockertest
    build:
      context: .
      dockerfile: DockerTest/Dockerfile
    networks:
      - backend
      - frontend
    ports:
      - 27221:80
    environment:
      - DHOST=mysql
    depends_on:
      - mysql
